#!/bin/bash

set -e

ORIGINAL_ARGS=("$@")

file_timestamp=$(date +%Y-%m-%d_%H)
LOG_DIR="$HOME/.local/logs/s_npm"
LOG_FILE="$LOG_DIR/run_err_${file_timestamp}.log"

mkdir -p "$LOG_DIR"


log_msg() {
  local level=$1
  local msg=$2
  local log_timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  echo "[$log_timestamp] [$level]: $msg" >> "$LOG_FILE"
}

error_handler() {
  local line_no=$1
  local exit_code=$2

  log_msg "ERROR" "Failed on line $line_no with exit code $exit_code. Args: ${ORIGINAL_ARGS[*]}"

  echo ""
  echo "[ERROR]: s_npm encountered an error"
  echo "Log persisted at $LOG_FILE"
}
trap 'error_handler $LINENO $?' ERR

signal_handler() {
  local signal_name=$1
  
  log_msg "INTERRUPT" "Process killed by signal ($signal_name). Args: ${ORIGINAL_ARGS[*]}"
  
  echo ""
  echo "[WARN]: s_npm was interrupted by $signal_name"
  echo "Details logged to: $LOG_FILE"

  exit 130 
}
trap 'signal_handler SIGINT' SIGINT
trap 'signal_handler SIGTERM' SIGTERM
trap 'signal_handler SIGHUP' SIGHUP
trap 'signal_handler SIGQUIT' SIGQUIT

precheck() {
  local is_install_cmd=false
  for arg in "$@"; do
    if [[ "$arg" == "install" || "$arg" == "i" || "$arg" == "ci" || "$arg" == "add" ]]; then
      is_install_cmd=true
      break
    fi
  done

  if [ "$is_install_cmd" = false ]; then
    echo "[ERROR]: s_npm is strictly an installation wrapper."
    echo "[INFO]: Allowed commands: install, i, ci, add."
    echo "[INFO]: Please use standard 'npm' for other commands."
    exit 1
  fi
}

main() {
  echo "[INFO]: Starting run: s_npm ${ORIGINAL_ARGS[*]}"

  RUN_SCRIPTS=false
  NPM_ARGS=()

  for arg in "$@"; do
    if [ "$arg" == "--with-scripts" ]; then
      RUN_SCRIPTS=true
    else
      NPM_ARGS+=("$arg")
    fi
  done


  if [ "$RUN_SCRIPTS" = true ]; then
    echo "[WARN]: Override running with npm lifecycle scripts"
    
    npm "${NPM_ARGS[@]}" --ignore-scripts=false
    
    echo "[INFO]: SUCCESS"
    echo "[INFO]: Installation complete"
  else
    echo "[INFO]: Running npm install without lifecycle scripts"
    
    npm "${NPM_ARGS[@]}" --ignore-scripts=true
    
    echo "[INFO]: SUCCESS"
    echo "[INFO]: Installation complete"
    
    npx --yes can-i-ignore-scripts
    
    echo "------------------------------------------------------"
    echo "[INFO]: To manually run a script for a trusted package, use:"
    echo "[CODE]: npm rebuild <package-name>"
    echo "[INFO]: To install and run automatically, use:"
    echo "[CODE]: s_npm install <package-name> --with-scripts"
  fi
}

precheck "$@"
main "$@"
